baseURL = "http://chermehdi.com/"
languageCode = "en-us"
title = "Mehdi Cheracher's Personnal blog"
theme = "terminal"
copyright = "Mehdi Cheracher"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "red"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # show selector to switch language
  showLanguageSelector = false
  # set theme to full screen width
  fullWidthTheme = true
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

[languages]
  [languages.en]
    languageName = "English"
    title = "Chermehdi"
    subtitle = "Mehdi Cheracher's personnal Blog"
    keywords = "Java,Java core,chermehdi,Java EE,design patterns"
    copyright = "Mehdi Cheracher, powered by Hugo"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "chermehdi"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"